Repository scil-vital/tractolearn, pull requests merged in 2023-02, with the labels that each got.

#33 ENH: Modernize package setup
  .github/workflows/test_package.yml
  README.md
  doc/conf.py
  pyproject.toml
  requirements/requirements.txt
  requirements/requirements_dmri_git.txt
  setup.py
  setup_helpers.py
  tox.ini
Labels: type:enhancement, type:documentation, type:infrastructure, type:packaging

#26 ENH: Add data fetcher
  .github/workflows/test_package.yml
  README.md
  pyproject.toml
  scripts/fetch_data.py
  scripts/tests/__init__.py
  scripts/tests/test_fetch_data.py
  tractolearn/tractoio/dataset_fetch.py
  tractolearn/tractoio/tests/__init__.py
  tractolearn/tractoio/tests/test_dataset_fetch.py
Labels: area:io, type:enhancement, type:documentation, type:infrastructure, type:testing

#36 ENH: Report slowest tests in `GitHub Actions`
  .github/workflows/test_package.yml
Labels: type:enhancement, type:infrastructure

#38 ENH: Remove the no longer necessary `info.py` file
  tractolearn/info.py
Labels: type:enhancement

#5 ENH: Add code format GitHub action workflow
  .github/workflows/check_format.yml
  .pre-commit-config.yaml
  README.md
Labels: type:enhancement, type:documentation, type:infrastructure

#40 DOC: Update GESTA paper information to published
  README.md
  doc/bibtex/Legarreta22_-_arXiv_-_GESTA.bib
  doc/bibtex/Legarreta23_-_MIA_-_GESTA.bib
Labels: type:documentation

#41 BUG: Duplication fixed to have generative_streamline_req_count_config
  tractolearn/tractoio/dataset_fetch.py
Labels: area:io, type:bug
